---
- name: Install prerequisites
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson
    - name: Ensure git is present
      apt: name=git state=present

- name: Install server
  hosts: all
  become: true
  roles:
    - common
    - { role: deploy, when: "vagrant is not defined", tags: ["deploy"] }
    - { role: provision, tags: ["provision"] }
    - { role: letsencrypt, tags: ["letsencrypt"], when: letsencrypt == 'enabled' }
