- name: reload nginx
  service: name=nginx state=reloaded
- name: compile app for production
  command: npm run build chdir=/srv/app
  environment:
    NODE_ENV: production
    REDADO_DOMAIN: "{{ domain }}"
    REDADO_API_DOMAIN: "{{ api_domain }}"
    REDADO_PROTOCOL: "{{ letsencrypt == 'enabled' | ternary('https','http') }}"
- name: reload redado webapp
  service: name=redado-app state=restarted enabled=yes
- name: reload redado api
  service: name=redado-api state=restarted enabled=yes
- name: find workers services
  find: paths=/etc/systemd/system patterns=redado-worker-*.service
  register: workers_services
- name: restart workers
  service: name={{ item.path | basename }} state=restarted enabled=yes
  with_items: "{{ workers_services.files }}"
