- name: Clone server repository
  git: repo=git@github.com:guilro/redado-server.git dest=/srv/server version=master accept_hostkey=yes
- name: Copy configuration domain files
  synchronize: src=../domain dest=/srv/server/
  notify:
    - reload redado api
- name: Copy workers files
  synchronize: src=../workers dest=/srv/server/
  notify:
    - check redado workers state
- name: Clone app repository
  git: repo=git@github.com:guilro/redado-app.git dest=/srv/app version=master accept_hostkey=yes
- name: Install app npm modules
  command: npm install chdir=/srv/app
  notify:
    - compile app for production
