---
- name: reload systemd
  command: systemctl daemon-reload
- name: reload nginx
  service: name=nginx state=reloaded
- name: restart redado api
  service: name=redado-api state=restarted enabled=yes
- name: find workers services
  find: paths=/etc/systemd/system patterns=redado-worker-*.service
  register: workers_services
- name: restart workers
  service: name={{ item.path | basename }} state=restarted enabled=yes
  with_items: "{{ workers_services.files }}"
  when: ansible is not defined
- name: install npm dependencies
  command: npm install chdir=/srv/workers/
